version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: drbimmer
      POSTGRES_PASSWORD: drbimmer
      POSTGRES_DB: drbimmer
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
  backend:
    build: ./backend
    volumes:
      - ./backend/app:/app/app
    environment:
      DATABASE_URL: postgresql://drbimmer:drbimmer@db:5432/drbimmer
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  db_data:
